### ISSUE TITLE
Empty task lists cause errors in 'show' and 'edit' for workflows

### ISSUE THREAD

**Issue by patrickmj** [NEU-Libraries/charon#1]
Remove all the tasks from a workflow in either design or manage, and save.

After saving, on the `show` page that it gets redirected to, it gives a `JSON::ParserError in WorkflowsController#show`

Similarly, if you back out to the list of workflows for the project and select one that has been saved with that problem, there's `JSON::ParserError in Workflows#edit`

Looks like a straightforward thing of `@workflow.task_list` being an empty string in the database in both places, making the parser choke.

From the trace on `#show`:

```
    @workflow = Workflow.find(params[:id])
    @project = @workflow.project
    @tasks = JSON.parse(@workflow.task_list)
```

**Comment by dgcliff** [comment]
Fixed with 81a36cd
